sudo: false
language: android
android:
    components:
        # SDK version
        - android-24
        # Use the latest revision of Android SDK Tools
        - tools
        # Build tools version
        - build-tools-26.0.2
        # Android Support Library (appcompat)
        - extra-android-support
        # Android Support Repository
        - extra-android-m2repository
before_install:
    - mkdir "$ANDROID_HOME/licenses" || true
    - cp ./licenses/* "$ANDROID_HOME/licenses/"

script:
    - ./gradlew test